branches:
  only:
    - main
    - develop
image: Visual Studio 2022
environment:
  EnableNuGetPackageRestore: true

build_script:
  - ps: .\build.ps1
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))


on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))